# https://github.com/googleapis/release-please-action

name: Release - angular-calendar-scheduler

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: write        # Necessario per creare tag e release
  pull-requests: write   # Necessario per creare PR di release

jobs:
  release:
    name: Release Please
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Solo sul branch main

    steps:
      - name: Release Please Action
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Default token, può essere omesso
          release-type: node
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
  publish:
    name: Publish to npm
    needs: release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
