# https://github.com/googleapis/release-please-action

name: Release - angular-calendar-scheduler

on:
  push:
    branches:
      - main

permissions:
  contents: write        # Necessario per creare tag e release
  pull-requests: write   # Necessario per creare PR di release

jobs:
  release:
    name: Release Please
    runs-on: ubuntu-latest

    steps:
      - name: Release Please Action
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Default token, può essere omesso
          release-type: node
          config-file: release-please-config.json
